services:
  postgres:
    container_name: mocadbdev_image
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=ymoyamac
      - POSTGRES_PASSWORD=ymoyamac
      - POSTGRES_DB=mocadbdev
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local